### ISSUE TITLE
Trigger expansion on `Tab`

### ISSUE THREAD

**Issue by olrtg** [olrtg/nvim-emmet#1]
Moving here https://github.com/olrtg/emmet-language-server/issues/28.

@kola-web we can continue here if you want.

**Comment by kola-web** [comment]
Very happily

**Comment by kola-web** [comment]
![image](https://github.com/olrtg/nvim-emmet/assets/46446884/7ef56fc3-657d-4856-b698-51e0a06ae74b)
This idea of ​​mine was generated by this option of vscode

**Comment by kola-web** [comment]
@olrtg I found a way to configure it based on the existing
example: 
```lua
      ['<tab>'] = cmp.mapping(function(fallback)
        if cmp.visible() then
          cmp.mapping.confirm({ select = true })()
        elseif has_words_before() then
          cmp.mapping.complete({
            config = {
              sources = {
                {
                  name = 'nvim_lsp',
                  entry_filter = function(entry)
                    return entry.source:get_debug_name() == 'nvim_lsp:emmet_language_server'
                  end,
                },
              },
            },
          })()
          cmp.mapping.confirm({ select = true })()
        else
          fallback()
        end
      end),

```
But sadly emmet_language_server non-standard HTML tags (e.g. custom view tags) are not supported

**Comment by olrtg** [comment]
Hey @kola-web! Yeah that's a problem even in vscode too.. What I was thinking is maybe you can just wrap everything that you're typing inside of a tag (for example `asdf` should produce `<asdf></asdf>`) without using the language server. I assume vscode does something similar because remember that this language server is just a wrapper of vscode-emmet-helper, so what I mean is that this language server doesn't have control over the completion logic.

And we can't really offer completion for whatever since it'll pollute the cmp results. See https://github.com/aca/emmet-ls/issues/55.

**Comment by kola-web** [comment]
Got it, thank you for your answer

**Comment by olrtg** [comment]
No worries! If you have some implementation maybe you can hang it out here for other people that may need this feature. I'm currently using vim-surround to wrap with tags.
