### ISSUE TITLE
Idea: Unwrap/Remove tag

### ISSUE THREAD

**Issue by Artikool5** [olrtg/nvim-emmet#10]
Hi, is it possible to get a function like wrap_with_abbreviation but to unwrap/remove the tag? This functionality exists in VSCode in command palette as "Emmet: Remove Tag".

Love the plugin and the LSP by the way, thank you for your work.

**Comment by olrtg** [comment]
Hey @Artikool5! sorry for the late response, very busy with work lately.

There's a high probability that you use something for surround motions such as `surround.nvim`. So, personally I just do `d` `s` `t` on the tag I want to remove while keeping the inner content.

Having this feature already in these type of popular plugins and also knowing that this feature will not interact with the emmet language server makes me believe that this is not a necessary feature in this plugin.

That being said, for now, I'll close this issue as "not planned" but still let me know if I'm missing something and maybe we can discuss it further.

Let me know if it helps.

**Comment by Artikool5** [comment]
Thank you @olrtg for finding time to answer!

I am kinda new to the vim/nvim and their ecosystems, so I chose to use something like Lazyvim for some time, like training wheels. You are absolutely right, I have something like surround and am using it extensively to add/change brackets or quotes, but it never crossed my mind to use it to delete something 😅. Especially for something like tags. Glory to the Treesitter I guess. 

Thank you for the answer one more time!
