### ISSUE TITLE
Feature: wrap abbreviation on each visually selected item

### ISSUE THREAD

**Issue by dpetka2001** [olrtg/nvim-emmet#5]
Given the following example
```
test
test
test
```
In vscode if you visually select all 3 lines and then do `Emmet: wrap with abbreviation` and you pass in the arguments `ul>li*` the result will be 
```
<ul>
	<li>test</li>
	<li>test</li>
	<li>test</li>
</ul>
```
But when using this plugin in Neovim the result is 
```
<ul>
	<li>
		test
		test
		test
	</li>
</ul>
```
Do you think this plugin could support abbreviation multiplication in visually selected items as well just like in insert mode with `emmet-language-server`?

**Comment by olrtg** [comment]
Hey! that's already possible but not directly I would say and I don't think I'm going to add a command for that specific case. In vim/neovim you can execute commands for each line in a selection. So you can do:

- Select the lines in visual line mode
- While in selection press the following `:norm YOUR_KEYBIND_FOR_WRAP_WITH_ABBREVIATION`.

https://vi.stackexchange.com/questions/4418/execute-normal-command-over-range

And that should do the work. Let me know if that helps.

**Comment by dpetka2001** [comment]
Thank you very much for your reply. If that works i'm totally ok with it. I will try it out after i get home later tonight.

**Comment by dpetka2001** [comment]
Do you happen to know how to pass the keybind which in my case is the default recommended by this plugin `<leader>xe`? If I change it to `xe` then it works. Do I have to do some kind of escaping for `<leader>` to be recognized by `:norm`? In my case `<leader>` is just space (`mapleader = " "`).

**Comment by dpetka2001** [comment]
> {commands} cannot start with a space.  Put a count of 1 (one) before it, "1 " is one space.                 

I managed to do it like this. Thank you again very much for your help.

**Comment by TurbulentTomato** [comment]
Can you tell me how to set up key binding for wrap with abbreviation? Thanks

**Comment by olrtg** [comment]
@TurbulentTomato an example is in the readme.

**Comment by 1096015776** [comment]
@dpetka2001 hey, maybe you can use mattn/emmet-vim 's emmet plugin, maybe Neovim not work. but you can remap to work, just add two map, such as:
map("v", "<c-y>", ':call emmet#expandAbbr(2,"")<cr>')
map("i", "<c-y>", '<c-r>=emmet#expandAbbr(0,"")<cr>')
It work so well with me

**Comment by 1096015776** [comment]
map("v", "<c-y>", ':call emmet#expandAbbr(2,"")<cr>')
map("i", "<c-y>", '<c-r>=emmet#expandAbbr(0,"")<cr>')

**Comment by 1096015776** [comment]
![image](https://github.com/user-attachments/assets/33488d94-ba95-48ac-8a0e-e83cf8337ebd)
GitHub some key upload issue, map like this

**Comment by dpetka2001** [comment]
@1096015776 Tnx, looks interesting. I'll check it out :smile:
