### ISSUE TITLE
Should use className instead of class in JSX/TSX files

### ISSUE THREAD

**Issue by b0o** [olrtg/nvim-emmet#6]
Wrapping with `a.foo.bar` expands to `<a href="" class="foo bar">` when it should be `<a href="" className="foo bar">`. Doing the expansion via the LSP with nvim-cmp results in the correct expansion.

**Comment by olrtg** [comment]
Hey @b0o! hope you're doing great.

Can't really reproduce on my end 🤔 are you on a `.jsx`/`.tsx` file? Or maybe are you sure that you don't have any configuration that you have left from working with solid js or something like that?

<img width="737" alt="Screenshot 2024-05-29 at 09 12 03" src="https://github.com/olrtg/nvim-emmet/assets/20072509/7e83014d-3a3a-433a-baf5-f30ad1fea6a7">

**Comment by b0o** [comment]
I get `className` when I expand via the `emmet_language_server` LSP using nvim-cmp, but when I try using `require('nvim-emmet').wrap_with_abbreviation()`, I get the `class`. I'm in a `.tsx` (typescriptreact filetype) file in a fresh Next.js project.


https://github.com/olrtg/nvim-emmet/assets/21299126/7193ab56-38d9-4a7c-8f22-f091e0fe6349

**Comment by olrtg** [comment]
Hey @b0o! People often come here to report things for the language server so I ended up misunderstanding you, sorry for that 💔. I saw your PR but as you mentioned, the fix should be more on the language server. Yesterday night I was working on the fix, submitting a PR in short.

**Comment by olrtg** [comment]
Fixed in https://github.com/olrtg/nvim-emmet/commit/cde4fb2968704aae5c18b7f8a9bc2508767bb78d! Update the language server (v2.6.0) and this plugin.

**Comment by b0o** [comment]
That fixed it, thank you!
