### ISSUE TITLE
Support for `.templ` templates

### ISSUE THREAD

**Issue by adonespitogo** [olrtg/nvim-emmet#7]

**Comment by olrtg** [comment]
This probably already works in the current state of the language server and this plugin. But I guess you'll have to add templ files to the filetypes list so the language server can attach to templ files. And that should be it. Let me know if it works.

**Comment by adonespitogo** [comment]
This is my lazy.nvim config: 

```lua
{
    "olrtg/nvim-emmet",
    ft = { "html", "templ", "erb" },
    config = function()
        vim.keymap.set({ "n", "v" }, "<leader>xe", require("nvim-emmet").wrap_with_abbreviation)
    end,
}
```
When e type `<leader>xe` the `Abbreviation:` prompt shows but nothing happens when I enter the abbrevation input.

**Comment by olrtg** [comment]
You should add the config to the language server not this plugin. https://github.com/olrtg/emmet-language-server/

**Comment by adonespitogo** [comment]
@olrtg 

Thanks, it works now :)
